In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
df_boston=pd.read_csv('boston_house_prices.csv', header=1)
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
y_df=df_boston.MEDV
y_df=np.array(y_df)
x_df=df_boston.LSTAT
x_df=np.array(x_df)
y_df=y_df.reshape(-1,1)
x_df=x_df.reshape(-1,1)

In [5]:
from sklearn import linear_model
regr=linear_model.LinearRegression()
regr.fit(x_df, y_df)
#regr.get_params(deep=True)
regr.coef_, regr.intercept_

(array([[-0.95004935]]), array([ 34.55384088]))

In [6]:
from sklearn.metrics import r2_score
#R_linear=r2_score(x_df, y_df)
trainpred=regr.predict(df_boston[['LSTAT']])
R_linear=r2_score(y_df, trainpred)
print(R_linear)

0.544146297586


In [7]:
from sklearn import linear_model
regr1=linear_model.LinearRegression()
regr1.fit(df_boston[['LSTAT', 'AGE']], df_boston.MEDV)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
trainpred1=regr1.predict(df_boston[['LSTAT','AGE']])
R_linear1=r2_score(y_df, trainpred1)
print(R_linear1)

0.551268937942


In [9]:
reg_b =linear_model.BayesianRidge()
model1=reg_b.fit(x_df, y_df)
reg_b.predict = model1.predict(df_boston[['LSTAT']])

R_Bayesian=r2_score(y_df, reg_b.predict)
print(R_Bayesian)

0.544144800128


C:\Users\saiva\Miniconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
from sklearn import linear_model
regr2=linear_model.LinearRegression()
regr2.fit(df_boston[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']], df_boston.MEDV)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
trainpred2=regr2.predict(df_boston[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']])
R_linear2=r2_score(y_df, trainpred2)
print(R_linear2)

0.740607742865


**EXTENDING THE EXAMPLE PROBLEM**

In [43]:
train, test = train_test_split(df_boston, test_size=0.25)

In [44]:
regr1=linear_model.LinearRegression()

In [45]:
x1_train=train[['LSTAT']]
y1_train=train[['MEDV']]

In [50]:
model=regr1.fit(x1_train, y1_train)

In [47]:
regr1.coef_, regr1.intercept_

(array([[-0.96786161]]), array([ 35.08238356]))

In [51]:
x1_test=test[['LSTAT']]
trainpred=model.predict(x1_test)

In [52]:
y1_test=test[['MEDV']]

In [55]:
r_linear_1= r2_score(y1_test, trainpred)

In [56]:
print(r_linear_1)

0.533938231588


**ANOTHER EXAMPLE WITH NON LINEAR TRANSFORMATION**

In [57]:
regr2=linear_model.LinearRegression()

In [65]:
x2_train=train[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
y2_train=train[['MEDV']]

In [68]:
model=regr2.fit(x2_train, y2_train)
regr2.coef_, regr2.intercept_

(array([[ -1.39359197e-01,   5.55182322e-02,   4.08487138e-02,
           2.06394698e+00,  -1.98582069e+01,   3.66213589e+00,
           6.19198421e-03,  -1.52477083e+00,   3.46644857e-01,
          -1.26489353e-02,  -1.02752677e+00,   9.29545508e-03,
          -5.48127337e-01]]), array([ 39.84806107]))

In [67]:
x2_test=test[['CRIM','ZN','INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT']]
y2_test=test[['MEDV']]

In [69]:
trainpred2=model.predict(x2_test)

In [70]:
r_linear_2=r2_score(y2_test, trainpred2)

In [71]:
print(r_linear_2)

0.760580437465
