In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split

In [2]:
diabetes= datasets.load_diabetes()
diabetes.data.shape

(442, 10)

In [3]:
diabetes_x=diabetes.data[:, np.newaxis, 2]
diabetes_x.shape

(442, 1)

In [4]:
x_train=diabetes_x[:-20]
x_test=diabetes_x[-20:]
y_train=diabetes.target[:-20]
y_test=diabetes.target[-20:]
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((422, 1), (20, 1), (422,), (20,))

In [5]:
regr=linear_model.LinearRegression()


In [6]:
regr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
regr.coef_

array([ 938.23786125])

In [8]:
np.mean((regr.predict(x_test)-y_test)**2)

2548.0723987259707

In [9]:
regr.score(x_test, y_test)

0.47257544798227119

***USING train_test_split() ON THE ABOVE DATASET TO COMPARE THE RESULTS***

In [44]:
dia_x_train, dia_x_test, dia_y_train, dia_y_test=train_test_split(diabetes_x, diabetes.target, test_size=0.2, random_state=80)

In [50]:
dia_x_train.shape, dia_x_test.shape, dia_y_train.shape, dia_y_test.shape

((353, 1), (89, 1), (353,), (89,))

In [45]:
regr1=linear_model.LinearRegression(normalize=True)

In [46]:
regr1.fit(dia_x_train, dia_y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [47]:
regr1.coef_

array([ 943.38719032])

In [48]:
np.mean((regr1.predict(dia_x_test)-dia_y_test)**2)

3660.4527290042543

In [49]:
regr1.score(dia_x_test, dia_y_test)

0.36075613518402622

***ANOTHER EXAMPLE***

In [85]:
data_xls=pd.read_excel('cheme_data_new.xlsx')
data_xls.head()


AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [86]:
data_xls.shape

(9568, 5)

In [174]:
y_df=data_xls.PE
y_df=np.array(y_df)
y_train, y_test=train_test_split(y_df, train_size=0.75)
y_test

array([ 427.11,  454.26,  435.81, ...,  432.53,  437.55,  486.3 ])

In [131]:
x_df=data_xls[['AT','V','AP','RH']]
x_df.shape

(9568, 4)

In [132]:
x_train, x_test=train_test_split(x_df, train_size=0.75)
x_train.shape

(7176, 4)

In [133]:
regr2=linear_model.LinearRegression(normalize=True)

In [134]:
model=regr2.fit(x_train, y_train)

In [135]:
trainpred=model.predict(x_test)

In [136]:
from sklearn.metrics import r2_score
R_linear=r2_score(y_test, trainpred)
print(R_linear)

-0.000425286859386


***ANOTHER APPROACH***

In [137]:
train, test= train_test_split(data_xls, train_size=0.75)

In [140]:
train.shape

(7176, 5)

In [152]:
x1_train=train[['AT','V','AP','RH']]

In [153]:
x1_train.shape

(7176, 4)

In [154]:
y1_train=train[['PE']]

In [155]:
y1_train.shape

(7176, 1)

In [156]:
regr_new=linear_model.LinearRegression()

In [161]:
model_new=regr_new.fit(x1_train, y1_train)

In [162]:
x1_test=test[['AT','V','AP','RH']]

In [175]:
y1_test=test[['PE']]
y1_test

PE
6392  467.44
2927  459.78
1361  487.30
7892  480.08
2326  468.28
3257  439.25
5950  442.12
32    440.98
5270  450.46
7767  487.49
7555  458.06
3611  438.29
8876  447.90
900   439.63
5261  474.26
5949  442.39
1988  436.55
6760  440.96
438   475.32
5520  453.81
3871  462.60
6914  477.78
1656  450.38
4650  438.51
144   442.70
3051  470.20
1845  441.75
7899  427.58
9023  449.99
2712  440.58
...      ...
1927  438.01
125   444.97
8111  458.57
5235  461.91
165   450.93
3834  493.90
7997  437.76
2369  457.26
5978  467.01
1898  452.00
5192  450.37
7852  438.00
6652  485.18
4378  431.96
9322  455.91
1220  484.04
9224  435.58
4167  444.90
6162  442.11
1638  472.65
2011  431.27
1490  426.15
5164  466.15
7166  481.44
7782  443.84
4749  443.35
8300  443.26
539   452.71
8477  491.97
5825  439.47

[2392 rows x 1 columns]

In [176]:
trainpred1=model_new.predict(x1_test)

In [177]:
R_linear1=r2_score(y1_test, trainpred1)
print(R_linear1)

0.926996519224
